<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drop files here or {select} files on You computer' => 'Перетащите файл сюда или {select} файл на вашем компьютере',
    'Your browser, unfortunately, not support the HTML5 File API.' => 'К сожалению, ваш браузер не поддерживает HTML5 File API. Обновите браузер или используйте Google Chrome',
    'select' => 'выберите',
];
